export const coreBasicPackage = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Core Packages",
  headline: "The Basic Package - $900",
  description: "Stationary Camera: 1",
  description2: "Stream/Audio Operator + Sound Board: 1",
  description3: "Raw Video Output (Copy of Recording): 1",
  description4:
    "Discount for Multiple Events (multiple days): -$100/day. ONE CAMERA: STATIONARY POINTING IN ONE DIRECTION (MINIMAL MOVEMENT) STREAMING WITH AUDIO. ONE VIDEOGRAPHER.",
  buttonLabel: "Get Started",
  imgStart: true,
  img: "/images/svg-image-1.svg",
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};

export const corePremiumPackage = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Core Packages",
  headline: "The Premium Package - $1,600",
  description: "Stationary Camera: 1",
  description2: "Stream/Audio Operator + Sound Board: 1",
  description3: "Camera Person + Camera: 1",
  description4: "Raw Video Output (Copy of Recording): 1",
  description5:
    "Discount for Multiple Events (multiple days): -$300/day. TWO CAMERAS: ONE STATIONARY POINTING IN ONE DIRECTION (MINIMAL MOVEMENT) AND ONE CAMERA WITH MULTI-DIRECTIONAL MOVEMENT. STREAMING WITH AUDIO. TWO VIDEOGRAPHERS.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: "/images/svg-image-2.svg",
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const coreUltimatePackage = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Core Packages",
  headline: "The Ultimate Package - $2,000",
  description: "Stationary Camera: 2",
  description2: "Stream/Audio Operator + Sound Board: 1",
  description3: "Camera Person + Camera: 1",
  description4: "Raw Video Output (Copy of Recording): 1",
  description5:
    "Discount for Multiple Events (multiple days): -$400/day. THREE CAMERAS: TWO STATIONARY POINTING IN TWO DIRECTIONS (MINIMAL MOVEMENT), AND ONE CAMERA WITH MULTI-DIRECTIONAL MOVEMENT. STREAMING WITH AUDIO. TWO VIDEOGRAPHERS.",
  buttonLabel: "Get Started",
  imgStart: true,
  img: "/images/svg-image-3.svg",
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};

export const comprehensiveBasicPackage = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Comprehensive Packages",
  headline: "The Basic Package - $1,300",
  description: "Stand Microphone: 2",
  description2: "Lapel Microphone: 4",
  description3: "Stationary Camera: 1",
  description4: "Stream/Audio Operator + Sound Board: 1",
  description5: "Raw Video Output (Copy of Recording): 1",
  description6:
    "Discount for Multiple Events (multiple days): -$100/day. ONE CAMERA: STATIONARY POINTING IN ONE DIRECTION (MINIMAL MOVEMENT) STREAMING WITH AUDIO. ONE VIDEOGRAPHER.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: "/images/svg-image-1.svg",
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const comprehensivePremiumPackage = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Comprehensive Packages",
  headline: "The Premium Package - $2,000",
  description: "Stand Microphone: 2",
  description2: "Lapel Microphone: 4",
  description3: "Stationary Camera: 1",
  description4: "Camera Person + Camera: 1",
  description5: "Stream/Audio Operator + Sound Board: 1",
  description6: "Raw Video Output (Copy of Recording): 1",
  description7:
    "Discount for Multiple Events (multiple days): -$300/day. TWO CAMERAS: ONE STATIONARY POINTING IN ONE DIRECTION (MINIMAL MOVEMENT) AND ONE CAMERA WITH MULTI-DIRECTIONAL MOVEMENT. STREAMING WITH AUDIO. TWO VIDEOGRAPHERS.",
  buttonLabel: "Get Started",
  imgStart: true,
  img: "/images/svg-image-2.svg",
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};

export const comprehensiveUltimatePackage = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Comprehensive Packages",
  headline: "The Ultimate Package - $2,400",
  description: "Stand Microphone: 2",
  description2: "Lapel Microphone: 4",
  description3: "Stationary Camera: 2",
  description4: "Camera Person + Camera: 1",
  description5: "Stream/Audio Operator + Sound Board: 1",
  description6: "Raw Video Output (Copy of Recording): 1",
  description7:
    "Discount for Multiple Events (multiple days): -$400/day. THREE CAMERAS: TWO STATIONARY POINTING IN TWO DIRECTIONS (MINIMAL MOVEMENT), AND ONE CAMERA WITH MULTI-DIRECTIONAL MOVEMENT. STREAMING WITH AUDIO. TWO VIDEOGRAPHERS.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: "/images/svg-image-3.svg",
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const extras = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  headline: "Extras",
  description:
    "Edited Video (Proper transitions/ Audio fixes/ Video cuts from multiple camera angles / etc.): 1 - $400",
  description2: "Private Web Site to Host Stream: 1 - $150",
  description3: "Stationary Camera: 2",
  description4:
    "Travel/Accommodation (outside of Ottawa/Gatineau) - Contact for Quote",
  buttonLabel: "Get Started",
  imgStart: true,
  img: "/images/svg-image-3.svg",
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};
